# Generated by Django 4.0 on 2022-10-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_logs', '0003_topic_owner_alter_entry_date_training_conducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='method_of_training',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
