# Generated by Django 4.1 on 2022-10-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_logs', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='GREEN TEAM', max_length=20),
        ),
    ]
