# Generated by Django 4.1 on 2022-10-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_logs', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Green Team', max_length=20),
        ),
    ]
